eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    preferIpAddress: true

server:
  port: 10044

spring:
  application:
    name: managementService
  datasource:
    url: jdbc:postgresql://localhost:5432/managementDb
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          validation:
            mode: none
    show-sql: true

jwt:
  secret:
    key: TrvkO1xPvqJImscCDocc8J7pvG3+GmLRORwwo6/9Ptl86AlmQ5kre1dx4hvv6IUtTE3yOBx+/hFOwGXctAlZ+OWDL9zSaPxkiDj9BCYROaI1FvfCxEyF8t2ScPJ3Rn/UoheFerStdyNpDzPttWy2FntxmefKXJzMKVYcxfg3A5bk8BdJJqY3boyQ7cqcQIJ2521KQ7BXkGEFrM6znLa2//hU3E939Y2Yr3JPXQz/EKvtfnhBzKvqMXG0zwvMI68lgQ4bNcXzRV3i5rk7W4lLsENH9uB/jFMAkrV/5cKR1ed5DkpORluMAI9y4OKfJ+CuuEweSAHotoVmaLcCOdFH7Q==
  expiration:
    ms: 600000
refreshToken:
  expiration:
    days: 10
  cookie-key: refresh-token
